services:
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    command: php -S 0.0.0.0:80 -t public
    ports:
      - "80:80"
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secrets!!'
      MYSQL_USER: 'challenge'
      MYSQL_PASSWORD: 'secrets!!'
      MYSQL_DATABASE: 'challenge'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
    mysqldata: {}
